# Intro

## Libraries

In [36]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [37]:
np.zeros(3)

array([0., 0., 0.])

## Jupyter básico

### Comandos

In [3]:
entero = 10
flotante = 12.
booleano = True
lista =[1,2,3]
diccionario = {'a':1,'b':2,'c':3}
set1 = (1,2,3,3,3,4)
set2 = (2,4,8)

In [4]:
entero

10

In [5]:
type(entero/3)

float

In [6]:
flotante

12.0

In [8]:
for element in lista:
    print(element**2)

1
4
9


In [29]:
lista[1:-1]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [20]:
lista = [*range(101)]

In [21]:
lista

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

### numpy

In [38]:
arr = np.arange(10)

In [40]:
arr.dtype

dtype('int32')

In [44]:
print(type(arr.shape))
print(len(arr.shape))

<class 'tuple'>
1


In [48]:
arr2 = np.full((4,3,2),'FOH')

In [49]:
arr2.shape

(4, 3, 2)

In [56]:
arr[arr % 3 == 0] = -1
arr

array([-1,  1,  2, -1,  4,  5, -1,  7,  8, -1])

In [55]:
# des de la posicion 5 empezando del final, hasta el final dando pasos negativos
arr[-5::-1]

array([5, 4, 3, 2, 1, 0])

In [63]:
arr3 = arr.reshape(5,-1)

In [64]:
arr3 * arr3

array([[ 1,  1],
       [ 4,  1],
       [16, 25],
       [ 1, 49],
       [64,  1]])

In [66]:
np.concatenate([arr3,arr3], axis=1)

array([[-1,  1, -1,  1],
       [ 2, -1,  2, -1],
       [ 4,  5,  4,  5],
       [-1,  7, -1,  7],
       [ 8, -1,  8, -1]])

In [67]:
set(arr).intersection(set(range(5,15)))

{5, 7, 8}

In [71]:
arr4 = np.arange(5,15)

In [72]:
np.intersect1d(arr,arr4)

array([5, 7, 8])

In [79]:
np.where(np.arange(9)<=np.arange(8,-1,-1),0,2)

array([0, 0, 0, 0, 0, 2, 2, 2, 2])

In [91]:
arr3

array([[-1,  1],
       [ 2, -1],
       [ 4,  5],
       [-1,  7],
       [ 8, -1]])

In [94]:
arr3.mean(axis=1)

array([0. , 0.5, 4.5, 3. , 3.5])

In [103]:
np.percentile(arr3,50)

1.5